# Setup
title:               Cuong Nguyen blog
tagline:             'memory dump'
description:         'Another machine learing blog'
url:                 https://cuongqn.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
github:
  repo: https://github.com/cuongqn
# About/contact
author:
  name:              Cuong Nguyen
  url:               https://twitter.com/cuong_qnguyen

# Gems
plugins:
  - jekyll-paginate
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
# Custom vars
version:             1.1.0
# google_analytics_id: UA-146052-15
